### ISSUE TITLE
无线网络的开关按钮显示异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/kylin-nm#10]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、点击任务栏中网络图标，查看无线网络开关按钮

预期结果：按钮显示正常

实际结果：按钮显示异常

**Comment by chenlelin** [comment]
原因为网络工具初始化时，无线网络开关在一个if语句中设置style不正确，已经更改

**Comment by liumin0322** [comment]
20200309版本测试通过
