### ISSUE TITLE
有线网络在没有连接网络时，上传数据不为0

### ISSUE THREAD

**Issue by liumin0322** [ukui/kylin-nm#11]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、系统未连接网络
2、点开网络连接，查看有线网络未连接的上传数据

预期结果：数据为0

实际结果：数据出现波动

**Comment by chenlelin** [comment]
目前更改为未连接有线网与无线网时，上传与下载数据和图标均不显示

**Comment by liumin0322** [comment]
20200309版本测试通过
