### ISSUE TITLE
手动设置ip，且通过终端能ping通其他ip，但是无法访问网页

### ISSUE THREAD

**Issue by liumin0322** [ukui/kylin-nm#12]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、手动配置ip，dns设为114.114.114.114
2、可通过终端ping通其他同事ip
3、打开终端，无法访问互联网

预期结果：可成果访问互联网

实际结果：在4.0.2商业版本中相同配置可访问互联网，在该版本中无法访问
![图片1](https://user-images.githubusercontent.com/48200161/76142494-54ffa100-60a9-11ea-85ce-e5d371bf6d5d.png)

**Comment by chenlelin** [comment]
dns配置文件没有配置好，通过修改配置文件，目前可正常访问网页

**Comment by liumin0322** [comment]
WSQ测试通过
