### ISSUE TITLE
wifi名称可修改

### ISSUE THREAD

**Issue by liumin0322** [ukui/kylin-nm#13]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、点击已连接的WiFi，弹出设置页面
2、修改网络名称，提示：新的设置已生效

预期结果：无法修改WiFi名称

实际结果：提示修改生效，但实际未生效

**Comment by chenlelin** [comment]
点击已连接的WiFi，弹出设置页面后，显示wifi名称的编辑框为不可编辑状态

**Comment by liumin0322** [comment]
20200321版本测试通过。
