### ISSUE TITLE
WiFi设置页面，设置手动IP等未生效

### ISSUE THREAD

**Issue by liumin0322** [ukui/kylin-nm#14]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、点击已连接的wifi，弹出网络设置界面
2、编辑IP设置，可设置为手动
3、弹出IP、网关、DNS等设置
4、填写后，点击保存

预期结果：成功

实际结果：弹出新的设置生效，但实际未生效

**Comment by chenlelin** [comment]
设置的是本机无线设备的IP，修改前后可通过ifconfig命令查看，inet会有变化。

**Comment by liumin0322** [comment]
20200321版本测试通过。
