### ISSUE TITLE
编辑网络设置界面，无输入内容检测

### ISSUE THREAD

**Issue by liumin0322** [ukui/kylin-nm#15]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开编辑网络设置界面
2、选择手动编辑
3、不填写ip，网关填写为1

预期结果：点击保存失败

实际结果：可成功保存，并提示设置生效

**Comment by chenlelin** [comment]
目前必须输入网络名称，且其他编辑框输入格式均正确，才能点击保存或确定按钮

**Comment by liumin0322** [comment]
20200321版本测试通过。
