### ISSUE TITLE
The laptop is not plugged into the network cable, the wired network shows that there is available ‘wired network 1’, click on the connection without any prompt message

### ISSUE THREAD

**Issue by liumin0322** [ukui/kylin-nm#16]

**Comment by chenlelin** [comment]
有一个包libnotify-bin出了问题。加入到kylin-nm依赖，连接网络时会卡顿。若不加入依赖，系统安装后再安装libnotify-bin，连接网络时不会卡顿。

**Comment by chenlelin** [comment]
未插入网线连接有线网络时会发出连接失败的信息。未发送信息的原因是依赖libnotify-bin包的notify-send命令，在部分电脑中无法执行。目前通过org.freedesktop.Notifications下org.freedesktop.Notifications接口发送桌面通知

**Comment by liumin0322** [comment]
Tested fail in the 20200410 version

**Comment by chenlelin** [comment]
plasma和meta均会注册名为org.freedesktop.Notifications的dbus服务，可在/usr/share/dbus-1/services/ 目录下看到这两个服务。若plasma抢先注册，则发送桌面通知会失败

**Comment by chenlelin** [comment]
plasma和meta均会注册名为org.freedesktop.Notifications的dbus服务，可在/usr/share/dbus-1/services/ 目录下看到这两个服务。若plasma抢先注册，则发送桌面通知会失败。
系统需要修改plasma的关于Notifications的dbus服务。

**Comment by liumin0322** [comment]
test passed in the 20200418
