### ISSUE TITLE
After the network settings and network status are modified, no notification will pop up

### ISSUE THREAD

**Issue by liumin0322** [ukui/kylin-nm#17]

**Comment by chenlelin** [comment]
有一个包libnotify-bin出了问题

**Comment by chenlelin** [comment]
依赖libnotify-bin包的notify-send命令，在部分电脑中无法执行。目前通过org.freedesktop.Notifications下org.freedesktop.Notifications接口发送桌面通知

**Comment by liumin0322** [comment]
Tested fail in the 20200410 version

**Comment by chenlelin** [comment]
plasma和meta均会注册名为org.freedesktop.Notifications的dbus服务，可在/usr/share/dbus-1/services/ 目录下看到这两个服务。若plasma抢先注册，则发送桌面通知会失败

**Comment by chenlelin** [comment]
所以系统要修改plasma和meta的dbus服务

**Comment by chenlelin** [comment]
plasma和meta均会注册名为org.freedesktop.Notifications的dbus服务，可在/usr/share/dbus-1/services/ 目录下看到这两个服务。若plasma抢先注册，则发送桌面通知会失败。
系统需要修改plasma的关于Notifications的dbus服务。

**Comment by liumin0322** [comment]
test passed in the 20200418
