### ISSUE TITLE
删除或者新建网路，任务栏显示网络连接界面，不会显示可用网络列表

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/kylin-nm#19]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200320-amd64.iso
测试环境：联想启天M415-N000台式机
测试步骤：
1任务栏-点击网络工具
2.新建网络/网络配置删除一个网络

预期结果： 任务栏显示网络连接界面显示正常
实际结果：删除或者新建网路，任务栏显示网络连接界面，不会显示可用网络列表

**Comment by chenlelin** [comment]
和 #27 是同一个bug

**Comment by 1216338727aa** [comment]
20200618 test passed
