### ISSUE TITLE
The network in the taskbar shows that it is not connected, but can access the Internet

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/kylin-nm#20]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200320-amd64.iso
测试环境：联想启天M415-N000台式机
测试步骤：
1.查看任务栏网络图标状态

预期结果：图标显示没有连接网络，系统就应该无网，打不开网页，ping不通
实际结果：任务栏网络图标显示没有连接网络，网络连接界面显示也没连接网络，但是可以上网，选择可以连接的网络，点击连接也链接不上，但是可以使用网络

**Comment by chenlelin** [comment]
初步判断是网络断开后，候补的网络被激活，但是界面未来得及刷新。

**Comment by chenlelin** [comment]
初步判断是网络断开后，候补的网络被激活的时间晚于界面刷新的时间。

**Comment by chenlelin** [comment]
已经添加网络同步功能，网络状态与外界保持一致

**Comment by 1216338727aa** [comment]
20200618  test passed
