### ISSUE TITLE
The network icon shows the connection. Using a browser to access Baidu fails, and ping fails.

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/kylin-nm#21]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200320-amd64.iso
测试环境：联想启天M415-N000台式机
测试步骤：
1.查看任务栏网络图标状态

预期结果：图标显示已连接网络，系统应该有网
实际结果：网络图标显示网路已连接，使用浏览器访问百度，没有网络，ping也ping不通

**Comment by chenlelin** [comment]
仍然有网络参数未配置正确，重新确认一下网络配置。这个问题与#12的bug属于同一类bug。

**Comment by 1216338727aa** [comment]
The 20200508 version passed the test
