### ISSUE TITLE
New network can create 2 same network names

### ISSUE THREAD

**Issue by liumin0322** [ukui/kylin-nm#24]
![2020-04-08 21-33-35屏幕截图](https://user-images.githubusercontent.com/48200161/78850011-aa342700-7a48-11ea-9e7a-16e48b68ce60.png)

**Comment by chenlelin** [comment]
可以创建两个同名网络，只是Kylin-nm未做处理

**Comment by chenlelin** [comment]
有线网存在同名网络是正常的。错误的原因是扩展时依据的是网络名称，导致几个同名网络均被扩展。解决方法是创建每个item时添加一个唯一标志，扩展时依据这个唯一标志进行判断扩展哪一个item。

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version

**Comment by liumin0322** [comment]
test passed in the 20200418
