### ISSUE TITLE
Unable to connect to last network automatically

### ISSUE THREAD

**Issue by ikeyhzj** [ukui/kylin-nm#26]
Version: 20.04LTS
iso: ubuntukylin-20.04-050803-amd64
Test environment: ThinkPad T480 desktop

Test steps:
Network tool - wired connection: if you are already connected to the network, reset the cable. The wired connection will not automatically connect to the network (the network you last connected to).
Wireless networks also have this phenomenon

Expected result: Can automatically connect to the last network
Actual result: Unable to connect automatically

**Comment by chenlelin** [comment]
Disconnect wired network for avoiding abnormal connection when plug in wired cable.

**Comment by 1216338727aa** [comment]
20200521 test passed
