### ISSUE TITLE
The theme icon corresponding to the gear icon in the lower left corner of the interface is not called correctly

### ISSUE THREAD

**Issue by Liang-zy** [ukui/kylin-nm#39]
界面内左下角齿轮图标对应的主题图标调用不对
![image](https://user-images.githubusercontent.com/39893452/87299218-31a89f00-c53e-11ea-91f8-0a7d9d712547.png)

**Comment by chenlelin** [comment]
目前设置按钮图标没有使用系统统一的图标

**Comment by chenlelin** [comment]
重新设置了主窗口左下角的图标样式

**Comment by Liang-zy** [comment]
0723 test passed
