### ISSUE TITLE
The content of the drop-down box in the "Join Network" pop-up window, please keep it aligned with the first content

### ISSUE THREAD

**Issue by Liang-zy** [ukui/kylin-nm#40]
’‘加入网络”弹窗中的下拉框内容，请与第一条内容保持对齐
![image](https://user-images.githubusercontent.com/39893452/87299384-7df3df00-c53e-11ea-9a72-1055e8bad2bd.png)

**Comment by chenlelin** [comment]
在下拉框的属性设置中加入 padding-left:17px;

**Comment by Liang-zy** [comment]
0723 test passed
