### ISSUE TITLE
Clicking on a blank area when expanding should be a shrinking effect, now it can remove the focus

### ISSUE THREAD

**Issue by Liang-zy** [ukui/kylin-nm#43]
展开时点击空白区应为收缩效果，现在是移除焦点
![image](https://user-images.githubusercontent.com/39893452/87299739-2bff8900-c53f-11ea-93d5-5edf8c295015.png)

**Comment by chenlelin** [comment]
正常的鼠标悬浮现象，当鼠标靠比较底部点击时，item收缩，鼠标会自然停到下一个item上方，下一个item出现悬浮效果。

**Comment by Liang-zy** [comment]
0723 test passed
