### ISSUE TITLE
有线连接网络默认为自动，界面上无法快捷设置IP

### ISSUE THREAD

**Issue by liumin0322** [ukui/kylin-nm#5]
点开可用有线连接网络，显示详细信息，但无法快速修改，只能通过网络连接程序设置

**Comment by chenlelin** [comment]
该功能已经重新添加，入口在有线网络扩展后出现的信息列表处，鼠标悬停会变为手掌形状。无线网络只有在连接后才能配置。

**Comment by liumin0322** [comment]
20200309版本测试通过
